version: '3.8'

services:
  builder:
    image: gradle:8.12-jdk23-alpine
    volumes:
      - build_output:/home/gradle/build
    working_dir: /home/gradle/project
    command: ["gradle", "build", "-x", "test"]
    user: gradle

  app:
    image: eclipse-temurin:23-jdk-alpine
    depends_on:
      - builder
    volumes:
      - build_output:/app
    entrypoint: ["java", "-jar", "/app/storagebot-0.0.1-SNAPSHOT.jar"]
    container_name: storagebot
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      org.name: "drib"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  build_output: